apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox3
spec:
  replicas: 3
  updateStrategy:
    type: OnDelete
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: busybox3
    spec:
      containers:
        - name: busybox3
          image: busybox3:1.34.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: busybox3-service
  labels:
    name: busybox3-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: busybox3
  type: ClusterIP
