apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox2
spec:
  replicas: 3
  updateStrategy:
    type: OnDelete
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: busybox2
    spec:
      containers:
        - name: busybox2
          image: busybox2:1.34.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: busybox2-service
  labels:
    name: busybox2-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: busybox2
  type: ClusterIP
