apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:1.34.0-uclibc
          ports:
            - containerPort: 80
          command:
            - '["/bin/sh"]'

---
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
  labels:
    name: busybox-service
spec:
  ports: []
  selector:
    app: busybox
  type: ClusterIP
