apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:1.34.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
  labels:
    name: busybox-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: busybox
  type: ClusterIP
