apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox1
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: busybox1
    spec:
      containers:
        - name: busybox1
          image: busybox1:1.34.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: busybox1-service
  labels:
    name: busybox1-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: busybox1
  type: ClusterIP
