apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.4.7
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  labels:
    name: haproxy-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: haproxy
  type: ClusterIP
