apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy1
spec:
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: haproxy1
    spec:
      containers:
        - name: haproxy1
          image: haproxy1:2.4.7
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy1-service
  labels:
    name: haproxy1-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: haproxy1
  type: ClusterIP
