apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy
spec:
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:2.2.17-alpine
          ports:
            - containerPort: 80
            - containerPort: 81

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  labels:
    name: haproxy-service
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
    - port: 8181
      targetPort: 81
      protocol: TCP
  selector:
    app: haproxy
  type: ClusterIP
