apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
        - name: nginx1
          image: nginx1:1.1.14
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx1-service
  labels:
    name: nginx1-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx1
  type: ClusterIP
